// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vldzttdzfqzqlrygytlv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZsZHp0dGR6ZnF6cWxyeWd5dGx2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc4MTI1MDIsImV4cCI6MjA1MzM4ODUwMn0.2nwKVUMHpX-r0Z7GMU2zNa878QSkOa_NTvLsK02yds4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);